# -*- coding: utf-8 -*-
"""Learning Neural Network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16wgSzX7pPNqlck2OoFF7mPBFJYTPjV5i

Visualizing Sigmoid Function
"""

# Import of Required Libraries
import numpy as np
import matplotlib.pyplot as plt

# Generating Input Dataset
input_data = np.linspace(-10,10,100) 
# 100 point between -10 to 10 has been generated and stored in input_data

# Testing and Verifying that the numbers are in the array of input_data and sorted
for i in range(10):
  print(input_data[i])

"""Sigmoid Function Declaration"""

# Define Sigmoid function
def sigmoid(x):
  activation_result = 1/( 1 + np.exp(-x))
  return activation_result

"""Output values of the sigmoid"""

# Output Values
calculated_data = sigmoid(input_data)

# Testing and Verifying that the numbers are in the array of calculated_data and sorted
for i in range(10):
  print(calculated_data[i])

"""Graphical Representation of the Sigmoid"""

# Plotting the graph of sigmoid
plt.plot(input_data,calculated_data)
plt.xlabel("Input")
plt.ylabel("Output")
plt.title("Sigmoid Function Visualization")
plt.show()